"""initial relational schema"""
from alembic import op
import sqlalchemy as sa

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_snapshots',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('resources', sa.JSON(), nullable=False),
    sa.Column('requests', sa.JSON(), nullable=False),
    sa.Column('content_digest', sa.String(length=64), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ordinal')
    )
    op.create_table('scopes',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('parent_id', sa.String(length=80), nullable=True),
    sa.Column('native_id', sa.String(length=600), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['scopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('grants', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=False),
    sa.Column('scope_id', sa.String(length=80), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('object_id', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('controls',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('scope_id', sa.String(length=80), nullable=False),
    sa.Column('latest_revision', sa.Integer(), nullable=False),
    sa.Column('lifecycle', sa.String(length=30), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_bindings',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('scope_id', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('native_id', sa.String(length=600), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_revisions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('control_id', sa.String(length=80), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(length=80), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('control_id', 'revision')
    )
    op.create_table('exceptions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('control_id', sa.String(length=80), nullable=False),
    sa.Column('scope_id', sa.String(length=80), nullable=False),
    sa.Column('requester_id', sa.String(length=80), nullable=False),
    sa.Column('approver_id', sa.String(length=80), nullable=True),
    sa.Column('resource_ids', sa.JSON(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('compensating_controls', sa.Text(), nullable=False),
    sa.Column('risk_owner', sa.String(length=160), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('native_status', sa.String(length=40), nullable=False),
    sa.Column('representation', sa.String(length=40), nullable=False),
    sa.Column('native_reference', sa.String(length=600), nullable=True),
    sa.Column('renewal_of', sa.String(length=80), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['renewal_of'], ['exceptions.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('implementations',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('revision_id', sa.String(length=80), nullable=False),
    sa.Column('template_id', sa.String(length=80), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.Column('document_digest', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['control_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id')
    )
    op.create_table('assessments',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.String(length=80), nullable=False),
    sa.Column('revision_id', sa.String(length=80), nullable=False),
    sa.Column('implementation_id', sa.String(length=80), nullable=False),
    sa.Column('snapshot_id', sa.String(length=80), nullable=False),
    sa.Column('scope_id', sa.String(length=80), nullable=False),
    sa.Column('author_id', sa.String(length=80), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['implementation_id'], ['implementations.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['control_revisions.id'], ),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['inventory_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ordinal')
    )
    op.create_table('rollouts',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('assessment_id', sa.String(length=80), nullable=False),
    sa.Column('author_id', sa.String(length=80), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('manifest_digest', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('delivery_state', sa.String(length=30), nullable=False),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('rollout_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('manifest_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rollout_id'], ['rollouts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rollout_id', 'actor_id')
    )
    op.create_table('receipts',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('rollout_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('disposition', sa.String(length=40), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rollout_id'], ['rollouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipts')
    op.drop_table('approvals')
    op.drop_table('rollouts')
    op.drop_table('assessments')
    op.drop_table('implementations')
    op.drop_table('exceptions')
    op.drop_table('control_revisions')
    op.drop_table('policy_bindings')
    op.drop_table('controls')
    op.drop_table('auth_sessions')
    op.drop_table('audit_events')
    op.drop_table('users')
    op.drop_table('scopes')
    op.drop_table('inventory_snapshots')
    # ### end Alembic commands ###
